name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    if: github.repository == 'khulnasoft/wasm-filters'  
    runs-on: ubuntu-latest
    steps:
      - name: Drafting release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
